GET http://127.0.0.1:3000/subscribers

###
POST http://127.0.0.1:3000/subscribers
Content-Type: application/json

{
  "name": "Anete Pik",
  "subscribedToChannel": "Web Developer"
}
### 
GET http://127.0.0.1:3000/
### 
POST http://127.0.0.1:3000/subscribers
Content-Type: application/json

{
  "name": "Rich Girl",
  "subscribedToChannel": "Compnay CTO"
}
###
GET http://127.0.0.1:3000/subscribers/62fbe573d0cda2afddbba553


### 
PATCH http://127.0.0.1:3000/subscribers/63047ba4294f53ca35321796
Content-Type: application/json

{
  "name": "Anete Pik",
  "subscribedToChannel": "Cloud developer"
}
### 
DELETE http://127.0.0.1:3000/subscribers/6303363a73c8e2652f3f467d
